### ISSUE TITLE
Sync the search on the intel bulletins with query

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#120]
On the page https://coh2stats.com/bulletins  we can do search - however it's not put into the path. 

We should modify this component to add search data into the url as a query, probably https://coh2stats.com/bulletins?search=text

This component is written at `packages/web/src/pages/bulletins/bulletinList.tsx`

We just need to add code into this function:
```
  const handleNameSearch = (e: ChangeEvent<HTMLInputElement>) => {
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      handleSearch(e.target.value, "bulletinName");
    }, 300);
  };

  const handleSearch = (value: string, column: string) =>
    setFilteredInfo({ ...filteredInfo, [column]: value });
```

To read the query you can use useQuery hook 
`import { useQuery } from "../../utils/helpers";`
https://github.com/petrvecera/coh2ladders/blob/master/packages/web/src/pages/stats/custom-stats-details.tsx#L28

**Comment by R4md4c** [comment]
Hey @petrvecera, I'm interested in this issue, but one question that's popped in my mind, do you want to add history capabilities to **push** a history of queries towards the browser stack? That would make users be able to navigate back and forth between search query.

**Comment by petrvecera** [comment]
Yes, I think we can use push() function from `const { push } = useHistory();`

I changing the url query similarly here:
https://github.com/petrvecera/coh2ladders/blob/master/packages/web/src/pages/stats/custom-stats.tsx#L170

Not sure if it's a best way to change the query. But it's working fine there.
