### ISSUE TITLE
Desktop App - add (google) analytics

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#130]
We should add google analytics (or any other analytics) to the app. 

I've read that there are some problems with Electron and google analytics but there seems to be ways to do it 
https://www.npmjs.com/package/electron-google-analytics

We can create any new project in google analytics for this

We basically just need how many people are using it and you can also track how many people are using the basic features. 
You might be surprised what people are actually doing most and sometimes you can find out that they don't use any feature because they might not know it's there. 

If google analytics can't be added - we can use something different.

**Comment by JohannesMerkt** [comment]
It would also be interessting to know with what kind of settings users are using the app.

**Comment by petrvecera** [comment]
@JohannesMerkt can you please add me on steam https://steamcommunity.com/id/pagep/  or/and discord `pagep#3171` thanks!

**Comment by petrvecera** [comment]
Hey I think we could do this via firebase - I didn't know we would be adding firebase to our app before I added the ticket. 
![image](https://user-images.githubusercontent.com/8086995/151706081-5375bdb5-6314-49b5-a610-6b122ef607dc.png)
![image](https://user-images.githubusercontent.com/8086995/151706102-8f1d6862-0f2e-4fc1-b8a2-4cb04bbb39e9.png)

So let's postpone this ticket

**Comment by petrvecera** [comment]
It looks like it works 👍 

![image](https://user-images.githubusercontent.com/8086995/152962245-6bc687b0-2303-460a-bfd6-f956af1b2028.png)


https://console.firebase.google.com/u/0/project/coh2-ladders-prod/analytics/app/web:NTQ3OTE0OGQtOTMzNi00ODMxLTkxYWItNGVhYTg2ZWM5M2Fh/overview/~2F%3Ft%3D1644313817677&fpn%3D293737053254&swu%3D1&sgu%3D1&sus%3Dupgraded&cs%3Dapp.m.dashboard.overview&g%3D1

**Comment by petrvecera** [comment]
https://github.com/petrvecera/coh2ladders/pull/150
