### ISSUE TITLE
Path to warnings.log - Unable to manually select folder.

### ISSUE THREAD

**Issue by MajorBonesLive** [petrvecera/coh2ladders#172]
When I click on the "select" button to change my warnings.log path, nothing happens. I have tried this on two different computers - same result. 

On one computer, it auto-selects my OneDrive folder.

**Comment by micronanomilo** [comment]
The same problem with me, the system didn't get my warning file right and thus it can't show the data

**Comment by petrvecera** [comment]
@MajorBonesLive  , @micronanomilo  what is the language of your windows? Also could you please post a screenshot how it looks like in your settings window of the app? Thank you

**Comment by micronanomilo** [comment]
I used my window 10 in EN-US, These are the information on 'about my computer': 
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎5/‎28/‎2021
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

this is a screenshot
![image](https://user-images.githubusercontent.com/100407197/155733737-d2b5c544-ba5f-4d32-b87e-5220f6e961ac.png)

**Comment by MajorBonesLive** [comment]
My windows language is English.
![Screenshot 2022-02-25 093313](https://user-images.githubusercontent.com/100253342/155742760-066c1dab-ba72-408b-91d9-db703af73c55.png)

**Comment by petrvecera** [comment]
Thanks for the reports, we will investigate 👍

**Comment by petrvecera** [comment]
Fixed in 1.3.2

**Comment by MajorBonesLive** [comment]
Download link not working:

![image](https://user-images.githubusercontent.com/100253342/155901550-0334c24d-b8d9-4533-8701-11819c3944d5.png)

**Comment by petrvecera** [comment]
Yeah sorry about that - the automated build process of the app takes longer than the updated push of the files with links. We will have to slow down the link pushing. It should be up now.

**Comment by MajorBonesLive** [comment]
Good deal, thanks!
