### ISSUE TITLE
BUG - Sometimes player cards doesn't have proper link / flag

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#176]
Sometimes the player names are lacking the flag and link to the username
![image](https://user-images.githubusercontent.com/8086995/155887331-397c1c6c-51aa-4720-8c47-70417dca149b.png)

**Comment by petrvecera** [comment]
I think it's related to the teams 
![image](https://user-images.githubusercontent.com/8086995/155890279-cdbfd356-aa99-435c-a676-6183de06bd37.png)

**Comment by JohannesMerkt** [comment]
So the reason why this sometimes happens is that these players have never played a solo game in the respective automatch category that is being played (2v2, 3v3 or 4v4). Therefore "member" data of this player never got assigned.
