### ISSUE TITLE
[Feature Request] Match stats vs. faction

### ISSUE THREAD

**Issue by LazyRen** [petrvecera/coh2ladders#24]
First of all, thank you for reviving coh2stats. I'm really happy to see the site again.

My request is that since we already have detail match info. present (such as commando / intel bulletins), add one more section to show what faction they played against & win ratio. (at least for 1vs1).

It would give such a good insights.

Thank you!

**Comment by petrvecera** [comment]
So you want to be able to pick a commander and see his winrate against different factions? We could add that "easily". The downside is that we don't really know if that commander was picked in the match, we only know that it was available for the winning player. 

I think the best approach would be combinations of the three commanders, to make a groups from them. However that would be "quite complicated", not that easy to implement. 

Thanks for the feature request! Will try to look into it in future.

**Comment by LazyRen** [comment]
No actually, just a vs win ration between factions.

For example, at the moment we can only view
USF win ration as a whole.
If would be better to see a section that shows win ratio
USF vs. OKW
USF vs. OST

Thank you.

**Comment by petrvecera** [comment]
Oh I see. Thanks for clarification. Yep it would make more sense to have this in 1-1. Will try to add it to the stats function.

**Comment by petrvecera** [comment]
I've been thinking about this feature for some time now - didn't have yet time to dig into it. I am considering adding this globally for all the match types. 

I think it would be interesting see the combinations. But I am not sure how to store the data information. It looks like really a lot of combinations. I am not sure how to approach keeping / storing the data. If we would consider just 1-1 we could do something like:
```
british:{
 wermacht: {
  wins: xx
  loses: xx
  },
  usf: {
   wins: xx
   loses: xx
  }
  ...
} ,
wermacht: {
  british: {
    wins:  xx
    loses: xx
  },
  usf: {
   wins: xx
   loses: xx
  }
}
```
This is very simplistic and straight forward approach however. It's great because when you want to display data for british you just look at the object and you have everything you need. However you can stop that we have duplicated data. Because with british vs wermacht we have the data but with wermacht vs brits it's the same data but reversed. 

Hm I just realized that it's basically something like heat map. In 4v4 very large one. Something like this.
![image](https://user-images.githubusercontent.com/8086995/117060742-8e6d8400-ad21-11eb-9be9-a85ac304aad2.png)


If anyone has idea how to store this dat efficiently in JavaScript please let me know.

**Comment by petrvecera** [comment]
I've got his figured out.

Single match analysis will do:

### Determine the team composition

- First go trough the match players and separate them into two teams. 
Go trough the team composition. And create the short description.

Description will be like this:
Axis:
```
Wehrmacht/Ostheer - W
OKW - O 
```
Allies:
```
Soviet - S
USF - U 
Brits - B 
```

In implementation we will create a factions = ["O", "W", "O"] for example in 3v3 game.  We will always run this code:
```
factions = ["O", "W", "O"]
factions.sort() // ["O", "O", "W"]
factions.join("") // "OOW"
```
This will ensure that we will always get the identificator `OOW` same even when the input will be  ["W", "O", "O"] for example. 

### Matchup indefiticator

We will than create a matchup indetificator like this:
"OOWxSSS" where axis team will be always first. It's definitely arbitrary format which we will need to have custom parsers for but it will be great for storing the data, it will be fast. And also it should be human readable.

### Store the actual data

The actual data will be stored in the object like this:

```
3v3: {
  "OOWxSSS": {
    wins: 45
    losses: 20
  }, 
  "OOOxSSS" {
    wins: 20
    losses: 50
  }
}
```
Where wins will be axis wins / losses. To get wins of SSS, you can just search SSS and swap the values wins/losses.

The data will be than displayed by heatmap https://nivo.rocks/heatmap/

**Comment by petrvecera** [comment]
This feature has been released https://coh2stats.com/stats/week/1620604800/1v1/wermacht?statsSource=all 

I wanted to make sure the routing work with it but I don't have time to look into. But the main thing is done!

**Comment by LazyRen** [comment]
Thank you for the feature update! Awesome!

However, I have one small suggestion regarding to the term.

![1](https://user-images.githubusercontent.com/8989837/119226954-a4af7880-bb46-11eb-9e6f-4e96d62aee77.PNG)

Above screenshot is from 2021-19th Top 200 1vs1.

As we all know, Axis has two factions.

Wehrmacht Ostheer (WM or Ostheer)
Oberkommando West (OKW)

Team composition matrix uses one character to represent the faction.
I see O stands for Ostheer & W stands for the West.
But it gives some confusing to the viewer.
If possible, would it be great to see WM & OKW on the Team composition matrix.

Or change Wermacht in Winrate grid to Ostheer so viewers can link faction name easily?

**Comment by petrvecera** [comment]
Yeah you are right. Actually it's the other way around. It's Wehrmacht and OKW 🤕 
![image](https://user-images.githubusercontent.com/8086995/119228322-c262ea80-bb12-11eb-9d41-3368a0737dd5.png)

I was thinking about putting whole name there, but than in 4v4 .. it needs to be 1 character or the label would be too long.
![image](https://user-images.githubusercontent.com/8086995/119228381-0ce46700-bb13-11eb-8c70-cac47f7cc7a0.png)

Fuck this is total mess 💢 ... in the COH2 source code / api / etc Relic is mixing all these things together, so for example Wehrmacht, Ostheer, German << is the same thing ... 

I should have picked Ostheer from the beginning but now it's too late - I use that term everyone ( and btw I have typo in it :D ) 

I am gonna try add legend to it, so it's more clear

**Comment by LazyRen** [comment]
Yeah adding legend will do just fine. Thank you.
