### ISSUE TITLE
[Feature Request] Implement "month stat so far" feature

### ISSUE THREAD

**Issue by LazyRen** [petrvecera/coh2ladders#51]
Hello,

Currently, week or month view shows below message if the full period has not been ended.

```default
We are currently not tracking any records for the month stats on timestamp 1625097600.
The statistics are run after the end of the day/week/month ~2AM UTC time.
```

But (I believe) many users want to see recent statistics before the month ends. Especially if half of the month has been passed.

So I suggest to enable Month view that shows (1st day of the month ~ day before today).

It will benefit user experience, since at the first click of week or month, it is very likely to give user `not tracking any record` error.

Thank you.

**Comment by petrvecera** [comment]
Should be fixed from now on.
