### ISSUE TITLE
Fix mode filtering on last matches table

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#77]
https://coh2stats.com/players/76561198034318060?view=matches

Filtering in the table doesn't work for the mode. Other works. 
![image](https://user-images.githubusercontent.com/8086995/134179336-b6554bbf-7e11-4768-9120-f6150b3abf36.png)

Most likely  issue with == vs === needs to be tested
https://github.com/petrvecera/coh2ladders/blob/master/packages/web/src/pages/matches/last-matches-table.tsx#L357

**Comment by Divyateja04** [comment]
I would like to try working on this, can you assign it to me?

**Comment by Divyateja04** [comment]
Hey, also, I generally use npm but installed yarn for this project but somehow it never runs completely....it always tells there's some problem with your network
For one date-fns it clearnly shows a link and says econnrefused and when i go to the link it gives it says package doesn't exist
https://registry.yarnpkg.com/date-fns/-/date-fns-2.24.0.tgz:

**Comment by Divyateja04** [comment]
Can you tell how to solve this?

**Comment by Divyateja04** [comment]
When I tried npm install in web folder and then run npm start, I get these errors:
![image](https://user-images.githubusercontent.com/28446977/135703482-1b9d4002-9439-479e-be11-1d113b9d3075.png)
Can you tell if you have any idea to solve them?

**Comment by Divyateja04** [comment]
okay so to solve them

change `import en from "javascript-time-ago/locale/en";` to `import en from "javascript-time-ago/locale/en.json";`

and also change catch statement in `player-card.tsx`

`
catch (e) {
        let errorMessage = "Failed to do something exceptional";
        if (e instanceof Error) {
          errorMessage = e.message;
        }
        console.error(e);
        setError(errorMessage);
      }
`

might help others working on it

**Comment by Divyateja04** [comment]
Sent the PR, Can you check it?

**Comment by petrvecera** [comment]
@Divyateja04 our project is not actually managed by npm. We are using `yarn`. To properly install all the packages. You need to do `yarn install` from the root folder of the project.

**Comment by Divyateja04** [comment]
yeah sent an updated PR, can you check? and about those messages, I figured it out later, so deleted them...sorry

**Comment by Divyateja04** [comment]
hey can you close this too?

**Comment by petrvecera** [comment]
Thanks for the contribution 👍 :octocat:
