### ISSUE TITLE
Add download button into match details - generate .json file

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#78]
- When you open match details for a player http://localhost:3000/players/76561198018614046?view=matches
- You can open full details modal
![image](https://user-images.githubusercontent.com/8086995/134585274-5289ae66-be5d-48f8-bbc3-e7525b6ecb54.png)

# Task: Add download button to the modal which will export the game data into .json file
![image](https://user-images.githubusercontent.com/8086995/134585405-6378cc22-b161-49d0-8828-14686e604bd9.png)
The button should be named "Download game data."  - or if you have better idea

You can do this by customizing the footer buttons on the modal https://ant.design/components/modal/#components-modal-demo-footer

The modal itself is defined in file `packages/web/src/pages/matches/last-matches-table.tsx` in component `ExpandedMatch`  line ~147

And the data we need to download are the props `record` which you will get in the component `ExpandedMatch` .

------------------------------------------------------
Another thing is - how to generate the json file from basically nothing? 

The filename should be probably `coh2stats_match_${record.id}.json`

I can't remember how do it. But if I am not mistaken we should be using blobs 
Something like: https://stackoverflow.com/a/44661948/1768843

**Comment by binkpitch** [comment]
I would like to try this. Can you assign this issue to me?

**Comment by petrvecera** [comment]
@binkpitch  sure! If you need help with anything. Let me know!
