### ISSUE TITLE
Remove beta label from the top site 

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#79]
There is no longer need for beta ribbon in the top left corner 
![image](https://user-images.githubusercontent.com/8086995/134588358-610dc5f1-6609-4fd0-b7f6-5c51566b7ee4.png)

We can remove it by deleting component `<BetaVersion />` in app.tsx `packages/web/src/App.tsx`
https://github.com/petrvecera/coh2ladders/blob/master/packages/web/src/App.tsx#L88

_We can leave the source code for that component still in. I think it's nice component we could use it somewhere else in future..._

**Comment by Divyateja04** [comment]
I'm willing to work on this, is it okay if I submit my PR during October so that it counts towards hacktoberfest

If yes, can you please assign this to me

**Comment by Divyateja04** [comment]
I did PR, can you check it?

**Comment by petrvecera** [comment]
Thanks, deployed and works https://coh2-ladders-dev.web.app/

**Comment by Divyateja04** [comment]
Honestly speaking it was a easy fix, If you have any other issues that are sorta easy, I can look into them too

**Comment by petrvecera** [comment]
@Divyateja04  this one should be also easy fix https://github.com/petrvecera/coh2ladders/issues/77 if you want 😉
