### ISSUE TITLE
Add links to the player names in the full match overview 

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/coh2ladders#88]
When you open the match over-view, for example on this player https://coh2-ladders-dev.web.app/players/76561198366572706?view=matches and click on some match. The player names are not links. They should be links as in the table. 

Task: Make the names links too. 
![image](https://user-images.githubusercontent.com/8086995/136084437-a4c52554-8761-4c72-928c-ec9808f718de.png)

The function which renders the player name is here:
`packages/web/src/pages/matches/match-details-table.tsx` line ~63

The code to make it a link should be:
```
<Link to={routes.playerCardWithId(convertSteamNameToID(playerInfo.profile["name"]))}> </Link>
```
^^ could probably work like this... 

But to explain: The path can be taken from function `routes.playerCardWithId(steamIDjustNumbers)` , the steam id is often saved as "/steam/1231231" so we can use function `convertSteamNameToID()` to get just the number.

**Comment by Milan218** [comment]
Hi, I would like to work on this issue, could you please assign it to me?

**Comment by Milan218** [comment]
Hi. I've created a pull request for this issue
